### ISSUE TITLE
Add to/Remove from a NodeBB when user enter/leave a specific level

### ISSUE THREAD

**Issue by Ghost-chu** [NodeBB-Community/nodebb-plugin-user-level#4]
It would be great if users could be added to a NodeBB group (and vice versa) after reaching a certain level. This would allow members with higher prestige to gain higher privileges through the group permissions system.

**Comment by barisusakli** [comment]
You should be able to do this with the core rewards system, see screenshot below.

![image](https://github.com/user-attachments/assets/72e4e8b5-1203-47f2-80d1-89a162041eb1)
